### ISSUE TITLE
Problem with "REST Explorer" - Maestro 6.0m11 

### ISSUE THREAD

**Issue by pcardinal** [jumpinjackie/mapguide-maestro#143]
Impossible to connect to REST service with Maestro 6.0m11 but no problem with Maestro 6.0m10.

Error Message thrown by Maestro when tying to connect to REST service

_"Could not load file or assembly 'RestSharp, Version=106.15.0.0, Culture=neutral, PublicKeyToken=598062e77f915f75'. Le fichier spécifié est introuvable.:_

Details

_System.IO.FileNotFoundException: Could not load file or assembly 'RestSharp, Version=106.15.0.0, Culture=neutral, PublicKeyToken=598062e77f915f75'. Le fichier spécifié est introuvable.
File name: 'RestSharp, Version=106.15.0.0, Culture=neutral, PublicKeyToken=598062e77f915f75'
   at Maestro.AddIn.Rest.UI.RestExplorer.btnConnect_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)_

I am using MapGuideOpenSource-4.0.0.10048 with IIS under Win10.

**Comment by jumpinjackie** [comment]
Re-opening and aborting the 6.0m12 release as the release artifact still has this issue.
