### ISSUE TITLE
Issue connecting Maestro 6 with SQL Server 2012 

### ISSUE THREAD

**Issue by leoparra** [jumpinjackie/mapguide-maestro#86]
HI there,
I havent been able to establish a connection to a SQL Server 2012 database.  I get the following message in Maestro when creating the resource

System.Net.WebException: The operation has timed out
   at System.Net.HttpWebRequest.GetResponse()
   at OSGeo.MapGuide.MaestroAPI.HttpServerConnection.OpenRead(String req) in C:\projects\mapguide-maestro\OSGeo.MapGuide.MaestroAPI\Http\HttpServerConnection.cs:line 1423
   at OSGeo.MapGuide.MaestroAPI.HttpServerConnection.GetSpatialContextInfo(String resourceID, Boolean activeOnly) in C:\projects\mapguide-maestro\OSGeo.MapGuide.MaestroAPI\Http\HttpServerConnection.cs:line 1210
   at Maestro.Editors.FeatureSource.CoordSysOverrideCtrl.btnLoadFromSc_Click(Object sender, EventArgs e) in C:\projects\mapguide-maestro\Maestro.Editors\FeatureSource\CoordSysOverrideCtrl.cs:line 146
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Any help will be greatly appreciated.  thanks in advanced

**Comment by jumpinjackie** [comment]
Any mapagent operation could timeout. That does not necessarily say anything about your SQL Server connectivity.

If you do a connection test on the Feature Source does it pass?

Can you connect to this SQL Server through [FDO Toolbox](https://github.com/jumpinjackie/fdotoolbox)? If so how many spatial contexts does it have?

**Comment by leoparra** [comment]
Hi Jackie,

I can connect to the database from a local installation of AIMS2016 and Maestro.  The problem started when I tried to connect from a remote server.  The database has 3 spatial contexts but maestro is not able to read them from the remote computer.
